### What is NumPy? 

- Simple Definition 
- NumPy stands for: 
- Numerical Python 
- It is a Python library used for:
  
• Fast mathematical calculations  
• Working with arrays  
• Scientific computing  
• Data analysis  
• Machine Learning 

### Easy Understanding

- Easy Understanding 
- Normal Python lists are slower for calculations. 
- NumPy provides:
    
• Faster arrays  
• Less memory usage  
• Powerful mathematical functions 

### Real-Life Analogy 

- Think like this:

• Python list = normal calculator  
• NumPy = scientific calculator 

- Because NumPy can handle:

• Large data  
• Matrix operations  
• Statistics  
• Linear algebra  
• Deep learning calculations  
very efficiently.

### Create NumPy Array 

- First import NumPy: 
- import numpy as np 

In [15]:
n1=[1,2,3,4,5]
n2=[5,6,7,8,9]
arr1=np.array([1,2,3,4,5])
arr2=np.array([5,6,7,8,9])
arr1,arr2

(array([1, 2, 3, 4, 5]), array([5, 6, 7, 8, 9]))

In [28]:
print("Addition :",arr1+arr2)
print("sub      :",arr1-arr2)
print("Division :", np.round(arr1 / arr2, 2))
print("mul      :",arr1*arr2)
print("module   :",arr1%arr2)  

Addition : [ 6  8 10 12 14]
sub      : [-4 -4 -4 -4 -4]
Division : [0.2  0.33 0.43 0.5  0.56]
mul      : [ 5 12 21 32 45]
module   : [1 2 3 4 5]


In [29]:
arr1+2

array([3, 4, 5, 6, 7])

In [30]:
arr2*2

array([10, 12, 14, 16, 18])

In [31]:
arr1+arr2+10

array([16, 18, 20, 22, 24])

In [33]:
arr1.tolist()

[1, 2, 3, 4, 5]

**Dimensions**

- the number of axes (directions) needed to represent data
   - 0D -> single value ,no dimension(scalar)
   - 1D → line ,list of values,one direction (vector)
   - 2D → table,rows+colomn (matrix)
   - 3D and above → collection of tables (tensor)
   - n-D tensor (4D,5D)

### 1. Create 1D Array 

In [34]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [35]:
type(arr)

numpy.ndarray

In [38]:
print("shape:",arr1.shape)  # shape means ex:2 rows,3 colns

shape: (5,)


In [40]:
print("ndim:",arr1.ndim)  # means 1 row-> 1 dimesion

ndim: 1


In [41]:
print("size:",arr1.size)  # total elements

size: 5


In [1]:
import numpy as np
l1=[10,20,30,40]
arr1=np.array(l1)
print('number of dimension:',arr1.ndim)
print('number of shape:',arr1.shape)
print('number of size:',arr1.size)

number of dimension: 1
number of shape: (4,)
number of size: 4


In [46]:
l2=np.array([1,3,45,6,78,9])
l2

array([ 1,  3, 45,  6, 78,  9])

**2. Create 2D Array**

In [47]:
l1=[10,20,30,40]
l2=[100,200,300,400]     #type-1
arr2=np.array([l1,l2])

In [48]:
arr2

array([[ 10,  20,  30,  40],
       [100, 200, 300, 400]])

In [49]:
type(arr2)

numpy.ndarray

In [51]:
print("no.of shape:",arr2.shape)
print("no.of size:",arr2.size)
print("no.of ndim:",arr2.ndim)

no.of shape: (2, 4)
no.of size: 8
no.of ndim: 2


In [52]:
arr=np.array([[1,2,3,4],[5,6,7,8]])    # type-2
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 3. Create 3D Array

In [53]:
arr1=np.array([[[1,2,3],[4,5,6],[5,6,7]]])  #type-1
arr1

array([[[1, 2, 3],
        [4, 5, 6],
        [5, 6, 7]]])

In [54]:
print("no.of shape:",arr1.shape)
print("no.of size:",arr1.size)
print("no.of ndim:",arr1.ndim)

no.of shape: (1, 3, 3)
no.of size: 9
no.of ndim: 3


In [60]:
# 3,2,4           #type-2
l1=[1,2,3,4]
l2=[l1,l1]
l3=[l2,l2,l2]
arr3=np.array(l3)
print(arr3)
print('*'*20)
print("no.of shape:",arr3.shape)
print("no.of size:",arr3.size)
print("no.of ndim:",arr3.ndim)

[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]
********************
no.of shape: (3, 2, 4)
no.of size: 24
no.of ndim: 3


**Special NumPy Arrays**

In [62]:
arr=np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [69]:
arr1=np.zeros((4,7))
arr2=np.array(arr1)
print(arr2)
print("="*30)
print("no.of shape:",arr2.shape)
print("no.of size:",arr2.size)
print("no.of ndim:",arr2.ndim)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
no.of shape: (4, 7)
no.of size: 28
no.of ndim: 2


### 5. Array of Ones

In [74]:
arr=np.ones((3))
print(arr)
print("="*30)
print("no.of shape:",arr.shape)
print("no.of size:",arr.size)
print("no.of ndim:",arr.ndim)

[1. 1. 1.]
no.of shape: (3,)
no.of size: 3
no.of ndim: 1


In [75]:
arr=np.ones((3,5))
print(arr)
print("="*30)
print("no.of shape:",arr.shape)
print("no.of size:",arr.size)
print("no.of ndim:",arr.ndim)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
no.of shape: (3, 5)
no.of size: 15
no.of ndim: 2


In [76]:
arr=np.ones((3,5,6))
print(arr)
print("="*30)
print("no.of shape:",arr.shape)
print("no.of size:",arr.size)
print("no.of ndim:",arr.ndim)

[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]
no.of shape: (3, 5, 6)
no.of size: 90
no.of ndim: 3


### 6. Create Identity Matrix 


In [77]:
arr1=np.eye(5)    # diagonals same
print(arr1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 7. Create Range of Numbers 

In [79]:
# Using arange() 
arr2=np.arange(1,11)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]


**With Step Size**

In [80]:
arr2=np.arange(1,11,2) #[start:stop:step---slicing]
print(arr2)

[1 3 5 7 9]


### 8. Create Evenly Spaced Values

In [82]:
# Using linspace()
# Meaning: 
# • Start = 0  
# • End = 1  
# • Total 5 values 

l1=np.linspace(0,1,5)
print(l1)

[0.   0.25 0.5  0.75 1.  ]


### 9. Random Array 

In [83]:
#Random decimal values between 0 and 1
arr=np.random.rand(1,10)
print(arr)

[[0.33089802 0.06355835 0.31098232 0.32518332 0.72960618 0.63755747
  0.88721274 0.47221493 0.11959425 0.71324479]]


In [84]:
arr=np.random.rand(4,4)
print(arr)

[[0.76078505 0.5612772  0.77096718 0.4937956 ]
 [0.52273283 0.42754102 0.02541913 0.10789143]
 [0.03142919 0.63641041 0.31435598 0.50857069]
 [0.90756647 0.24929223 0.41038292 0.75555114]]


### 10. Random Integer Array 

In [86]:
# Meaning: 
# • Numbers from 1 to 9  
# • Shape = 3 rows × 4 columns 
arr=np.random.randint(1,10,(3,4))
print(arr)

[[1 1 9 9]
 [4 9 3 7]
 [6 8 9 5]]


#### Convert List to NumPy Array

In [87]:
l1=[1,2,3]
arr=np.array(l1)
print(arr)

[1 2 3]


In [88]:
type(arr)

numpy.ndarray

#### NumPy Attributes

- In NumPy, attributes are properties that give information about a 
- NumPy array. 
- Think like this:
    
• Methods → perform actions  
• Attributes → give information

### Important NumPy Attributes 

In [91]:
l1=[1,2,3,4,5]
l2=[5,6,7,8,9]
arr1=np.array(l1)
arr2=np.array(l2)
arr3=np.array([l1,l2])
print(arr3)

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [97]:
#shape
# Tells: 
# Number of rows and columns 

print("no of shape:",arr3.shape)  # 2 rows and 5 columns

no of shape: (2, 5)


In [100]:
# 2. ndim 
# Tells: 
# It is a 2D array
# Number of dimensions

print("no of ndim:",arr3.ndim)

no of ndim: 2


In [105]:
# 3. size 
# Tells: 
# Total = elements
# like=2*5=10
# Total number of elements 

print("total size:",arr3.size)

total size: 10


In [104]:
# 4. dtype 
# Tells:
# - int32 
# - (or int64 depending on system) 
# - Datatype of elements 

print("dtypes:",arr3.dtype)

dtypes: int64


In [106]:
# 5. itemsize 
# Tells: 
# Memory used by one element (in bytes)
#Meaning: 
#• Each integer uses 4 bytes memory 
print("itemsize:",arr3.itemsize)

itemsize: 8


In [107]:
# 6. nbytes 
# Tells: 
# Total memory used by array
# Formula: 
# Total Bytes = size × itemsize 

print("total bytes:",arr3.nbytes)

total bytes: 80


In [108]:
# 7. T 
# Used for: 
# Transpose of array 
# Rows become columns.and columns becomes rows
print("transpose:",arr3.T)

transpose: [[1 5]
 [2 6]
 [3 7]
 [4 8]
 [5 9]]


In [109]:
# 8. real 
# Returns real part. 
# Used mostly in complex numbers. 
a = np.array([1+2j, 3+4j]) 
a.real


array([1., 3.])

In [110]:
# 9. imag 
# Returns imaginary part. 
a.imag

array([2., 4.])

In [111]:
# 10. flat 
# Converts array into iterator.
for i in arr.flat:
    print(i)

1
2
3


### Important NumPy Methods — Easy Explanation

In [114]:
data=np.array([[1,2,3,4,5],[6,7,8,9,1]])
print(data)
print("="*30)
print("no.of shape:",data.shape)
print("no.of size:",data.size)
print("no.of ndim:",data.ndim)

[[1 2 3 4 5]
 [6 7 8 9 1]]
no.of shape: (2, 5)
no.of size: 10
no.of ndim: 2


In [116]:
# 1. min() 
# Finds smallest value.
data.min()

np.int64(1)

In [117]:
# 2. max() 
# Finds largest value.
data.max()

np.int64(9)

In [118]:
# 3. sum() 
# Finds total sum.
data.sum()

np.int64(46)

### Row-wise and Column-wise Sum

#### Column-wise

In [119]:
# Explanation: like this
# • 3+8 = 11  
# • 1+2 = 3  
# • 5+6 = 11  
data.sum(axis=0)

array([ 7,  9, 11, 13,  6])

#### Row-wise

In [120]:
data.sum(axis=1)

array([15, 31])

### 4. reshape() 

In [122]:
#Changes shape of array
l1=np.array([1,2,3,4,5,6])
l1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

### 5. count_nonzero() 

In [124]:
#Counts non-zero values.
l2=np.array([1,2,0,4,5,0])
np.count_nonzero(l2)

np.int64(4)

### 6. sort()

In [125]:
# sort the elements
l2=np.array([1,2,9,4,5,10])
np.sort(l2)

array([ 1,  2,  4,  5,  9, 10])

In [128]:
# Sort 2D Array 
# np.sort(arr)
#Row-wise sorting happens.
np.sort(arr)

array([1, 2, 3])

#### 7. flatten()

In [130]:
#Converts multi-dimensional array into 1D array.
l2.flatten()

array([ 1,  2,  9,  4,  5, 10])

#### 8. mean() 

In [132]:
 
# Finds average.
l3=np.array([1,2,9,4,5,10])
l3.mean()

np.float64(5.166666666666667)

### std

In [134]:
#Finds standard deviation. 
np.round(l3.std())

np.float64(3.0)

#### variance

In [136]:
# find the variance
np.round(l3.var())

np.float64(11.0)

### 11. argmax()

In [139]:
#Returns index of maximum value.
l1=np.array([1,2,9,4,5,10])
l1.argmax()

np.int64(5)

### 12. argmin() 

In [140]:
# Returns index of minimum value
l1.argmin()

np.int64(0)

### 13. unique()

In [143]:
# Finds unique values.
arr6=np.array([1,2,3,4,4,5,6,7,7,8,9,9,4,6,7])
np.unique(arr6)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])